[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.4",
    "sseclient>=0.0.27",
    "telethon>=1.40.0",
    "urllib3>=2.5.0",
]
